<?php

namespace App\Http\Controllers;

use App\Models\StripePayments;
use Illuminate\Http\Request;
use Stripe\Stripe;
use Stripe\Charge;
use Stripe\Refund;
use Exception;
use Illuminate\Support\Facades\Auth;

class StripePaymentController extends Controller
{
    public function showForm()
    {
        $user = Auth::user();
        $price = request('price', 0);
        return view('stripe_payment_form', compact('price', 'user'));
    }

    public function pay(Request $request)
    {
        $request->validate([
            'stripeToken' => 'required',
            'email' => 'required|email',
            'amount' => 'required|numeric|min:0.01',
        ]);

        try {
            // Stripe::setApiKey(env('STRIPE_SECRET_KEY'));
            Stripe::setApiKey(config('services.stripe.secret'));

            $charge = Charge::create([
                'amount' => $request->amount * 100, // Convert to cents
                'currency' => env('STRIPE_CURRENCY'),
                'source' => $request->stripeToken, // Use the token generated by Stripe
                'description' => 'Payment from ' . $request->email,
                
            ]);

            $payment_intent = StripePayments::create([
                'payment_id' => $charge->id,
                'payer_email' => $request->email,
                'amount' => $request->amount,
                'currency' => env('STRIPE_CURRENCY'),
                'payment_status' => $charge->status,
            ]);

            return view('payment_success', [
                'transactionId' => $charge->id,
                'paymentMethod' => 'stripe',
                'payment_intent' => $payment_intent,
            ]);
        } catch (\Exception $e) {
          //  \Log::error('Stripe Payment Error: ' . $e->getMessage());
            return view('payment_error', ['message' => $e->getMessage()]);
        }
    }

    public function refund(Request $request, $paymentIntentId)
    {
        Stripe::setApiKey(env('STRIPE_SECRET_KEY'));
        $amount = $request->input('amount') * 100;
        $refund = Refund::create([
            'charge' => 'ch_3S8ihYBWJnkf7DLT1GqIvqyh',
            'amount' => $amount,
        ]);
        if ($refund->status === 'succeeded') {
            return back()->with('status', 'Remboursement effectué.');
        }
        return back()->with('status', 'Erreur lors du remboursement.');
    }

    // historique des paiements
    public function paymentHistory()
    {
        $payments = StripePayments::orderBy('created_at', 'desc')->get();
        return view('payment_history', compact('payments'));    
    }
}
