<?php

namespace App\Http\Controllers;

use App\Models\StripePayments;
use Illuminate\Http\Request;
use Stripe\Stripe;
use Stripe\Charge;

class StripePaymentController extends Controller
{
    public function showForm()
    {
        return view('stripe_payment_form');
    }

    public function pay(Request $request)
    {
        $request->validate([
            'stripeToken' => 'required',
            'email' => 'required|email',
            'amount' => 'required|numeric|min:0.01',
        ]);

        try {
            // Stripe::setApiKey(env('STRIPE_SECRET_KEY'));
            Stripe::setApiKey(config('services.stripe.secret'));

            $charge = Charge::create([
                'amount' => $request->amount * 100, // Convert to cents
                'currency' => env('STRIPE_CURRENCY'),
                'source' => $request->stripeToken, // Use the token generated by Stripe
                'description' => 'Payment from ' . $request->email,
            ]);

            StripePayments::create([
                'payment_id' => $charge->id,
                'payer_email' => $request->email,
                'amount' => $request->amount,
                'currency' => env('STRIPE_CURRENCY'),
                'payment_status' => $charge->status,
            ]);

            return view('payment_success', [
                'transactionId' => $charge->id,
                'paymentMethod' => 'stripe',
            ]);
        } catch (\Exception $e) {
            \Log::error('Stripe Payment Error: ' . $e->getMessage());
            return view('payment_error', ['message' => $e->getMessage()]);
        }
    }
}
